# Where things are
source:      .
destination: ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
data_dir: ./_data
collections:
  cv:
    output: true
    permalink: /cv/:path/

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      ["gems", "result", "default.nix", "vendor", ".idea"]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
plugins:      [jekyll-paginate]

# Conversion
markdown:    kramdown
# highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

# Serving
detach:  false
port:    4000
host:    0.0.0.0
baseurl: "" # does not include hostname

# Backwards-compatibility
relative_permalinks: false

# Outputting
permalink:     /blogs/myblog/:title
paginate_path: /page/:num
timezone:      Europe/Ljubljana

quiet:    false
defaults: []

# Markdown Processors
maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
  fenced_code_blocks: true

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:      true
  footnote_nr:   1
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  enable_coderay:   false

  syntax_highlighter_opts:
    wrap:              div
    line_numbers:      inline
    line_number_start: 1
    tab_width:         4
    bold_every:        10
    css:               style

redcloth:
  hard_breaks: true

paginate: 8

name: Matej Cotman's Blog
author: Matej Cotman
nick: matejc
description: open-source is liberating
url: https://blog.matejc.com
email: cotman.matej@gmail.com
disqus_shortname: matejcsblog
urls:
  github: https://github.com/matejc/
